[build]
  command = "npm run build:smart"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# API redirects for all subdomains
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Removed conflicting admin subdomain rule - using _redirects file instead
