[build]
  command = "npm run build:smart"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# API redirects for all subdomains
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Admin subdomain routing
[[redirects]]
  from = "/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = {Host = ["admin.swellfocusgrid.com"]}

# Admin root fallback
[[redirects]]
  from = "/*"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = {Host = ["admin.swellfocusgrid.com"]}

# Default - serve client app for main domain
[[redirects]]
  from = "/*"
  to = "/client/index.html"
  status = 200
